### ISSUE TITLE
Build broken?

### ISSUE THREAD

**Issue by yozhijk** [SaschaWillems/Vulkan-glTF-PBR#12]
I am getting a bunch of build errors in VS2017 related to stbi after tinygltf update: https://github.com/SaschaWillems/Vulkan-glTF-PBR/commit/db99bb6760507359b6a681c4b6e8a709c9787206

1>c:\dev\pbr\base\stb_image.h(764): error C2371: 'stbi__context': redefinition; different basic types
1>c:\dev\pbr\base\stb_image.h(764): note: see declaration of 'stbi__context'
1>c:\dev\pbr\base\stb_image.h(771): error C2084: function 'void stbi__start_mem(stbi__context *,const stbi_uc *,int)' already has a body
1>c:\dev\pbr\base\stb_image.h(770): note: see previous definition of 'stbi__start_mem'
1>c:\dev\pbr\base\stb_image.h(780): error C2084: function 'void stbi__start_callbacks(stbi__context *,stbi_io_callbacks *,void *)' already has a body
1>c:\dev\pbr\base\stb_image.h(779): note: see previous definition of 'stbi__start_callbacks'

**Comment by SaschaWillems** [comment]
Can you please check again with the latest commit? I did some clean up and removed an unused tinygltf include in the main unit that may have caused this problem.

This builds without problems for me on VS2017 and Android Studio.

**Comment by yozhijk** [comment]
Works now, thanks!
