### ISSUE TITLE
Segfaults in some models within animations

### ISSUE THREAD

**Issue by fl0at88** [SaschaWillems/Vulkan-glTF-PBR#14]
likes this
https://sketchfab.com/models/844ba0cf144a413ea92c779f18912042

**Comment by SaschaWillems** [comment]
I'm already aware of this. That model's bone count is higher than the max. number of bones currently supported by this example.

**Comment by fl0at88** [comment]
The model display correct when i set the value to 128

**Comment by SaschaWillems** [comment]
I have increased the limit to 128 joints and also introduced a define in the loader and the vertex shader that you can increase if you need more.
