### ISSUE TITLE
Emissive map after tone mapping?

### ISSUE THREAD

**Issue by neXyon** [SaschaWillems/Vulkan-glTF-PBR#15]
In your pbr.frag shader, you apply the emissive texture after tone mapping, just adding what you read out of the texture.

Shouldn't the emissive map be applied before tone mapping and when you read the texture don't you have to transform it from sRGB to linear RGB (since the standard mentions the emissive texture to be in sRGB space)?

**Comment by neXyon** [comment]
Also: the baseColorFactor is applied too late as well?

**Comment by SaschaWillems** [comment]
Yes, that's not right. I'll fix this.

**Comment by SaschaWillems** [comment]
Looks like the [Khronos reference implementation als behaves like this](https://github.com/KhronosGroup/glTF-WebGL-PBR/).

That's what m shaders are based on, so you may want to open an issue over there too.

**Comment by neXyon** [comment]
Comparing these two here:

Khronos: https://github.com/KhronosGroup/glTF-WebGL-PBR/blob/master/shaders/pbr-frag.glsl
Yours: https://github.com/SaschaWillems/Vulkan-glTF-PBR/blob/master/data/shaders/pbr.frag

Emissive texture: in the Khronos shader it's applied in lines 302/303 including SRGB to linear conversion, while you don't convert in lines 201/202. Gamma correction happens in your case in line 198, before the emissive map, while in the Khronos implementation it happens in line 318, so afterwards. The Khronos implementation doesn't have tone mapping. Physically it makes no sense to have tone mapping before the light emission of a material though.

As for the base color factor this is applied directly at the beginning in the Khronos shader with the base color texture in lines 232 to 236. You apply the base color factor in line 207 while the base color texture is read with the `ALBEDO` define in lines 126, 170 and 180, not considering the base color factor in all cases.

**Comment by SaschaWillems** [comment]
My sample no longer uses the pbr.frag shader, so please don't compare that. I have switched to the Khronos sample implementation some time ago, which can be found in https://github.com/SaschaWillems/Vulkan-glTF-PBR/blob/master/data/shaders/pbr_khr.frag.

**Comment by neXyon** [comment]
Ah, my bad then. I didn't look at this one, since I thought that's maybe the shader used for the specular glossiness KHR extension. You could remove the old shader to avoid further confusion.

**Comment by SaschaWillems** [comment]
Yes, you're completely right. It's no longer used anyway, so I'll remove it to avoid further confusion.
