### ISSUE TITLE
glm/glm.hpp not found

### ISSUE THREAD

**Issue by gokulsukumar03** [SaschaWillems/Vulkan-glTF-PBR#16]
Build command failed.
Error while executing process /Users/admin/Library/Android/sdk/cmake/3.10.2.4988404/bin/cmake with arguments {--build /Users/admin/Desktop/Vulkan/gltfsample/Vulkan-glTF-PBR-master/android/app/.externalNativeBuild/cmake/debug/armeabi-v7a --target native-lib}
[1/10] Building C object CMakeFiles/native-app-glue.dir/Users/admin/Library/Android/sdk/ndk-bundle/sources/android/native_app_glue/android_native_app_glue.c.o
[2/10] Linking C static library libnative-app-glue.a
[3/10] Building CXX object CMakeFiles/native-lib.dir/Users/admin/Desktop/Vulkan/gltfsample/Vulkan-glTF-PBR-master/base/VulkanAndroid.cpp.o
[4/10] Building CXX object CMakeFiles/native-lib.dir/Users/admin/Desktop/Vulkan/gltfsample/Vulkan-glTF-PBR-master/external/imgui/imgui_demo.cpp.o
[5/10] Building CXX object CMakeFiles/native-lib.dir/Users/admin/Desktop/Vulkan/gltfsample/Vulkan-glTF-PBR-master/external/imgui/imgui_draw.cpp.o
[6/10] Building CXX object CMakeFiles/native-lib.dir/Users/admin/Desktop/Vulkan/gltfsample/Vulkan-glTF-PBR-master/base/VulkanExampleBase.cpp.o
FAILED: CMakeFiles/native-lib.dir/Users/admin/Desktop/Vulkan/gltfsample/Vulkan-glTF-PBR-master/base/VulkanExampleBase.cpp.o 
/Users/admin/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ --target=armv7-none-linux-androideabi19 --gcc-toolchain=/Users/admin/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64 --sysroot=/Users/admin/Library/Android/sdk/ndk-bundle/sysroot  -Dnative_lib_EXPORTS -I../../../../../../base -I../../../../../../external -I../../../../../../external/glm -I../../../../../../external/gli -I/Users/admin/Library/Android/sdk/ndk-bundle/sources/android/native_app_glue -isystem /Users/admin/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include -isystem /Users/admin/Library/Android/sdk/ndk-bundle/sources/android/support/include -isystem /Users/admin/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++abi/include -isystem /Users/admin/Library/Android/sdk/ndk-bundle/sysroot/usr/include/arm-linux-androideabi -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -mthumb -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -std=c++11 -std=c++11 -DVK_USE_PLATFORM_ANDROID_KHR -DVK_NO_PROTOTYPES -O0 -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/native-lib.dir/Users/admin/Desktop/Vulkan/gltfsample/Vulkan-glTF-PBR-master/base/VulkanExampleBase.cpp.o -MF CMakeFiles/native-lib.dir/Users/admin/Desktop/Vulkan/gltfsample/Vulkan-glTF-PBR-master/base/VulkanExampleBase.cpp.o.d -o CMakeFiles/native-lib.dir/Users/admin/Desktop/Vulkan/gltfsample/Vulkan-glTF-PBR-master/base/VulkanExampleBase.cpp.o -c /Users/admin/Desktop/Vulkan/gltfsample/Vulkan-glTF-PBR-master/base/VulkanExampleBase.cpp
In file included from /Users/admin/Desktop/Vulkan/gltfsample/Vulkan-glTF-PBR-master/base/VulkanExampleBase.cpp:9:
In file included from ../../../../../../base/VulkanExampleBase.h:46:
../../../../../../base/camera.hpp:12:10: fatal error: 'glm/gtc/quaternion.hpp' file not found
#include <glm/gtc/quaternion.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
[7/10] Building CXX object CMakeFiles/native-lib.dir/Users/admin/Desktop/Vulkan/gltfsample/Vulkan-glTF-PBR-master/src/main.cpp.o
FAILED: CMakeFiles/native-lib.dir/Users/admin/Desktop/Vulkan/gltfsample/Vulkan-glTF-PBR-master/src/main.cpp.o 
/Users/admin/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ --target=armv7-none-linux-androideabi19 --gcc-toolchain=/Users/admin/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64 --sysroot=/Users/admin/Library/Android/sdk/ndk-bundle/sysroot  -Dnative_lib_EXPORTS -I../../../../../../base -I../../../../../../external -I../../../../../../external/glm -I../../../../../../external/gli -I/Users/admin/Library/Android/sdk/ndk-bundle/sources/android/native_app_glue -isystem /Users/admin/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include -isystem /Users/admin/Library/Android/sdk/ndk-bundle/sources/android/support/include -isystem /Users/admin/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++abi/include -isystem /Users/admin/Library/Android/sdk/ndk-bundle/sysroot/usr/include/arm-linux-androideabi -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -mthumb -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -std=c++11 -std=c++11 -DVK_USE_PLATFORM_ANDROID_KHR -DVK_NO_PROTOTYPES -O0 -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/native-lib.dir/Users/admin/Desktop/Vulkan/gltfsample/Vulkan-glTF-PBR-master/src/main.cpp.o -MF CMakeFiles/native-lib.dir/Users/admin/Desktop/Vulkan/gltfsample/Vulkan-glTF-PBR-master/src/main.cpp.o.d -o CMakeFiles/native-lib.dir/Users/admin/Desktop/Vulkan/gltfsample/Vulkan-glTF-PBR-master/src/main.cpp.o -c /Users/admin/Desktop/Vulkan/gltfsample/Vulkan-glTF-PBR-master/src/main.cpp
In file included from /Users/admin/Desktop/Vulkan/gltfsample/Vulkan-glTF-PBR-master/src/main.cpp:25:
In file included from ../../../../../../base/VulkanExampleBase.h:46:
../../../../../../base/camera.hpp:12:10: fatal error: 'glm/gtc/quaternion.hpp' file not found
#include <glm/gtc/quaternion.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
[8/10] Building CXX object CMakeFiles/native-lib.dir/Users/admin/Desktop/Vulkan/gltfsample/Vulkan-glTF-PBR-master/external/imgui/imgui_widgets.cpp.o
[9/10] Building CXX object CMakeFiles/native-lib.dir/Users/admin/Desktop/Vulkan/gltfsample/Vulkan-glTF-PBR-master/external/imgui/imgui.cpp.o
ninja: build stopped: subcommand failed.

**Comment by SaschaWillems** [comment]
glm is included as a submodule, so either check out recursively or manually init and pull them as described in the [readne](https://github.com/SaschaWillems/Vulkan-glTF-PBR#cloning).
