### ISSUE TITLE
How to pass (GLTF)model name to main.cpp

### ISSUE THREAD

**Issue by gokulsukumar03** [SaschaWillems/Vulkan-glTF-PBR#21]
Hi SaschaWillems,
I want to pass the model name from activity to main.cpp. 
In the example, defualt give (std::string sceneFile = assetpath + "models/DamagedHelmet/glTF-Embedded/Box.gltf")

I like to pass (GLTF) model name from the activity. KIndly let me know how to do this.

**Comment by SaschaWillems** [comment]
Afaik that requires the use of JNI, which is the interopt between Java an C++ on Android. Never done that, so I can't help with that.
