### ISSUE TITLE
Crashes when displaying multi animation glTF

### ISSUE THREAD

**Issue by Peach1** [SaschaWillems/Vulkan-glTF-PBR#22]
An assert fails when importing this low poly glTF model with multiple animations:

[fox.gltf.zip](https://github.com/SaschaWillems/Vulkan-glTF-PBR/files/2999017/fox.gltf.zip)

The same gltf works fine in other viewers: https://gltf-viewer.donmccurdy.com/

The glTF appears to parse correctly but it asserts and crashes with vertex buffer out of range before the glTF is rendered to the screen.

This project is one of the few C++ glTF viewers that displays animation, so I find it a very valuable reference for animated glTF implementation, is it possible to fix this import?

**Comment by SaschaWillems** [comment]
Thanks for letting me know. All the gltf files I tested only had one animation, and I wasn't able to test with files containing multiple animations.

I'll take a look at your sample and try to fix this.

**Comment by SaschaWillems** [comment]
This was actually pretty trivial to fix. The app now also supports primitives without indices and then just renders them using their vertices.

The fox renders fine for me, and switching animations works fine too.
