### ISSUE TITLE
MacOS build might be easy to achieve

### ISSUE THREAD

**Issue by cesss** [SaschaWillems/Vulkan-glTF-PBR#24]
Hi!

I'm trying to build Vulkan-glTF-PBR on MacOS, and, although you are not listing the Mac as a supported platform, I think the build should be quite easy to achieve. I just installed the Vulkan SDK on my Mac, and set all the environment variables. When invoking cmake with Vulkan-glTF-PBR it successfully detects the SDK, as well as the draco compression (which I built in advance as you suggest in the docs.

I tried to tweak CMakeLists.txt (adding -DVK_USE_PLATFORM_MACOS_MVK and removing the xcb dependency within the USE_D2D_WSI block, which is the block that is being executed on my Mac), and then added a VK_USE_PLATFORM_MACOS_MVK block to main.cpp, but then of course the build fails anyway, because the Mac platform is not implemented in the VulkanExample class. I looked at your Vulkan demos repository, and it does support the Mac, and you have a more complete VulkanExample class there, but I guess it's not a matter of just copying a couple of files, or maybe is it?

**Comment by cesss** [comment]
Bummer... just tried to build your Vulkan samples repository, and found that the MacOS build isn't done with CMake, but with Xcode. I always avoid Xcode (I have it installed, but avoid it completely, as I'm Terminal-only for development), so I'm pausing building your code for the moment, because I guess I'll need to do some modifications in order to build with CMake. Anyway, I'm going to start a ticket in your samples repo, just in case anybody has a custom CMake build already.

**Comment by Radagan** [comment]
This is an old post, but I would like to build this sample for macOS also. I expect to encounter issues with latest Vulkan, as I did with the main samples library, but I hit weird errors prior to that. 

Has anyone here managed to build this sample since this post back in 2019?

It is a very exciting sample. I'm trying to load the Amazon Lumberyard Bistro scene after converting it to glTF 2.0 in Blender from FBX. Any and all advice welcome. Here's where the build dies for me at the moment:

```
-- The C compiler identification is AppleClang 13.1.6.13160021
-- The CXX compiler identification is AppleClang 13.1.6.13160021
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using module to find Vulkan
-- Found Vulkan: /usr/local/lib/libvulkan.dylib (found version "1.3.216") 
-- /usr/local/lib/libvulkan.dylib
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/rolfhunt/Development/Azure/mobeus/github/Vulkan-glTF-PBR/build
(base) rolfhunt@Rolfs-MBP build % cmake --build .
[ 10%] Building CXX object base/CMakeFiles/base.dir/__/external/imgui/imgui.cpp.o
[ 20%] Building CXX object base/CMakeFiles/base.dir/__/external/imgui/imgui_demo.cpp.o
[ 30%] Building CXX object base/CMakeFiles/base.dir/__/external/imgui/imgui_draw.cpp.o
[ 40%] Building CXX object base/CMakeFiles/base.dir/__/external/imgui/imgui_widgets.cpp.o
[ 50%] Building CXX object base/CMakeFiles/base.dir/VulkanAndroid.cpp.o
[ 60%] Building CXX object base/CMakeFiles/base.dir/VulkanExampleBase.cpp.o
[ 70%] Building CXX object base/CMakeFiles/base.dir/VulkanglTFModel.cpp.o
/Users/rolfhunt/Development/Azure/mobeus/github/Vulkan-glTF-PBR/base/VulkanglTFModel.cpp:9:9: warning: #pragma once in main file [-Wpragma-once-outside-header]
#pragma once
        ^
/Users/rolfhunt/Development/Azure/mobeus/github/Vulkan-glTF-PBR/base/VulkanglTFModel.cpp:742:2: warning: non-void function does not return a value in all control paths [-Wreturn-type]
        }
        ^
/Users/rolfhunt/Development/Azure/mobeus/github/Vulkan-glTF-PBR/base/VulkanglTFModel.cpp:760:2: warning: non-void function does not return a value in all control paths [-Wreturn-type]
        }
        ^
3 warnings generated.
[ 80%] Linking CXX static library libbase.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libbase.a(VulkanAndroid.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libbase.a(VulkanAndroid.cpp.o) has no symbols
[ 80%] Built target base
[ 90%] Building CXX object src/CMakeFiles/Vulkan-glTF-PBR.dir/main.cpp.o
[100%] Linking CXX executable ../bin/Vulkan-glTF-PBR
CMakeFiles/Vulkan-glTF-PBR.dir/main.cpp.o:1:1: error: source file is not valid UTF-8
<CF><FA><ED><FE><U+0007><U+0000><U+0000><U+0001><U+0003><U+0000><U+0000><U+0000><U+0001><U+0000><U+0000><U+0000><U+0005><U+0000><U+0000><U+0000><E8><U+0004><U+0000><U+0000><U+0000> <U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0019><U+0000><U+0000><U+0000>X<U+0004><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><D0>F<U+0008><U+0000><U+0000><U+0000><U+0000><U+0000><U+0008><U+0005><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><C8>F<U+0008><U+0000><U+0000><U+0000><U+0000><U+0000><U+0007><U+0000><U+0000><U+0000><U+0007>
^
[Lots and lot of errors that are similar deleted...]
```

**Comment by Radagan** [comment]
@SaschaWillems I fixed the macOS build issues and sent you a PR. Please have a look when you can and see what you think.

**Comment by Radagan** [comment]
This issue can be closed. After PR, code build fine on macOS.
