### ISSUE TITLE
BRDF LUT generation uses wrong scissor dimensions?

### ISSUE THREAD

**Issue by a-day-old-bagel** [SaschaWillems/Vulkan-glTF-PBR#26]
The scissor extent width and height are set to the general window width and height variables instead of to the dimensions being used to generate the BRDF LUT (the variable "dim").

This is obviously super minor, but it just seemed like not what you'd want to do in general and if for some reason the BRDF LUT was generated after the window size had been changed to something smaller than 512x512 I suppose it would break. Right now it just works because the generation happens before the default window size has a chance to be overwritten with anything too small, I'm guessing.

I'd say they ought to each just be set to "dim" instead.

https://github.com/SaschaWillems/Vulkan-glTF-PBR/blob/d0a195e6b6ea882436e70a777bf82a7f02f8b13c/src/main.cpp#L1045

https://github.com/SaschaWillems/Vulkan-glTF-PBR/blob/d0a195e6b6ea882436e70a777bf82a7f02f8b13c/src/main.cpp#L1046

**Comment by SaschaWillems** [comment]
Thx for letting me know. This was also wrong for the cube map generation.
