### ISSUE TITLE
F (l,h) debugNamesEquation,Whats is Use How its defined....Its third Party ??

### ISSUE THREAD

**Issue by arunkiddo** [SaschaWillems/Vulkan-glTF-PBR#28]
There are few debugNamesEquation in main.cpp ( "none", "Diff (l,n)", "F (l,h)", "G (l,v,h)", "D (h)", "Specular) How did you define what is the definition of F (l,h).How to initialise a new color change in debug view

**Comment by SaschaWillems** [comment]
> How did you define what is the definition of F (l,h).

Naming is based on the official Khronos PBR glTF setup. 

> How to initialise a new color change in debug view

Can you be more specific?

**Comment by arunkiddo** [comment]
There is a debug view option,In that only you have defined  ( "none", "Diff (l,n)", "F (l,h)", "G (l,v,h)", "D (h)", "Specular) these now can I add few other colors ??

**Comment by SaschaWillems** [comment]
Sure, just add your view to the [fragment shader](https://github.com/SaschaWillems/Vulkan-glTF-PBR/blob/master/data/shaders/pbr_khr.frag#L394).
