### ISSUE TITLE
recompile the vulkan shader 

### ISSUE THREAD

**Issue by pure-water** [SaschaWillems/Vulkan-glTF-PBR#32]
Hi how i can fiddle with the new shader effects?

 The environment is windows/visual studio  How I can managed to recompile for example,  pbr_khr.frag to *.sprv?  I clean and recompile does not seem to take effects?  The spriv shaders taking effects are the ones in the repo.  Any quick hint? 

  Regards
  Yao

**Comment by SaschaWillems** [comment]
How do you recompile the shaders? Make sure the .spv is outputted to the correct directory.

**Comment by pure-water** [comment]
How do you recompile the shaders?
   >>Actually that is the question. I recompile the whole solution in visual studio which does not seem to be recompiling the shader?

**Comment by SaschaWillems** [comment]
Shaders are not automatically recompiled along with the C++ code. You either have to manually invoke e.g. the glslangcompiler or use something like my [SPIR-V plugin](https://github.com/SaschaWillems/SPIRV-VSExtension) for VS that allows you to recompile from within the IDE.
