### ISSUE TITLE
Skin weight with (0, 0, 0, 0)

### ISSUE THREAD

**Issue by syoyo** [SaschaWillems/Vulkan-glTF-PBR#38]
Sometimes skin weights become all zeros(0, 0, 0, 0)
(e.g. Maya2glTF https://github.com/WonderMediaProductions/Maya2glTF exported glTF model)

For such weight input, output vertex position in vertex shader become  NaN or invalid, resulting no display of a skinned mesh.

Possible solution is...

Set weights to `(1, 0, 0, 0)` for `(0, 0, 0, 0)` in `VulkanglTFModel.hpp`,

https://github.com/SaschaWillems/Vulkan-glTF-PBR/blob/750db74be3814d88c169387ea0b8485f705e322c/base/VulkanglTFModel.hpp#L783

(Assuming the first joint id is the root node?)

 or add check of weights value in PBR shader.

https://github.com/SaschaWillems/Vulkan-glTF-PBR/blob/master/data/shaders/pbr.vert#L41

FYI, it looks three.js handles this situation well.

**Comment by SaschaWillems** [comment]
Can you provide a smaple model that exhibits this problem? That would make it easier to fix the problem.

**Comment by syoyo** [comment]
[skin-weight.zip](https://github.com/SaschaWillems/Vulkan-glTF-PBR/files/4211814/skin-weight.zip)

Here is the test scene.

![skin-maya](https://user-images.githubusercontent.com/18676/74624010-236e7680-518a-11ea-9194-3be88a7fc9bf.PNG)

And here is Maya skin weight visualization just FYI.

**Comment by syoyo** [comment]
https://github.com/KhronosGroup/glTF/issues/1213

This issue thread includes the  discussion about zero weights.

**Comment by SaschaWillems** [comment]
I have pushed a fix for this. Skin weights with a length of zero will now be set to 1,0,0,0. With that change your sample model is now properly displaying.

**Comment by syoyo** [comment]
Thanks!
