### ISSUE TITLE
Android Build Issue

### ISSUE THREAD

**Issue by nishantdande** [SaschaWillems/Vulkan-glTF-PBR#4]
Android NDK: Found platform level in ./project.properties. Setting APP_PLATFORM to android-23.    
Android NDK: WARNING: APP_PLATFORM android-23 is higher than android:minSdkVersion 19 in ./AndroidManifest.xml. NDK binaries will *not* be comptible with devices older than android-23. See https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md for more information.    
Android NDK: Your APP_BUILD_SCRIPT points to an unknown file: ./jni/Android.mk    
Android/Tools/android-sdk-windows/ndk-bundle/build/core/add-application.mk:101: *** Android NDK: Aborting...    .  Stop.
Error building project!

**Comment by SaschaWillems** [comment]
Some Android build files were missing. Please try again.
