### ISSUE TITLE
animationTimer is scaled by 0.75

### ISSUE THREAD

**Issue by syoyo** [SaschaWillems/Vulkan-glTF-PBR#41]
https://github.com/SaschaWillems/Vulkan-glTF-PBR/blob/72aa7a7a193c022c0e4653a98d70cd80d289be97/src/main.cpp#L2005

@SaschaWillems animationTimer is scaled by 0.75. Is there any reason to do this?

**Comment by syoyo** [comment]
glTF uses `seconds` for animation time data, so it should not be multiplied by 0.75

**Comment by SaschaWillems** [comment]
You're right. This was probably a left-over from debugging. I'll fix that.
