### ISSUE TITLE
Using copyCmd instead of blitCmd, when blitting mipmaps

### ISSUE THREAD

**Issue by mciragan** [SaschaWillems/Vulkan-glTF-PBR#5]
In base/VulkanglTFModel.hpp, 233, 247 and 263 vkCmdPipelineBarrier() is used with copyCmd, that has been freed in device->flushCommandBuffer(copyCmd, copyQueue, true);, line 194. It should use blitCmd. It runs on Nvidia though, but on Android, MotoZ crashes. When using blitCmd, then it works nicely.

Thanks,
Mete

**Comment by SaschaWillems** [comment]
Thx for noticing! 👍
