### ISSUE TITLE
android studio build error

### ISSUE THREAD

**Issue by hliwen** [SaschaWillems/Vulkan-glTF-PBR#59]
In file included from /home/hlw/Demo/Vulkan-glTF-PBR/base/VulkanglTFModel.cpp:16:
In file included from /home/hlw/Demo/Vulkan-glTF-PBR/base/VulkanglTFModel.h:18:
/home/hlw/Demo/Vulkan-glTF-PBR/base/VulkanDevice.hpp:58:4: error: use of undeclared identifier 'vkGetPhysicalDeviceProperties'

**Comment by SaschaWillems** [comment]
I have pushed a fix for this. It builds fine for me now.
