### ISSUE TITLE
Effect of SRGBtoLinear

### ISSUE THREAD

**Issue by kyamant** [SaschaWillems/Vulkan-glTF-PBR#66]
Question:
I am experimenting with PBR using glTF, using this project as a reference(pbr_khr.frag shader specifically).
The straightforward task of displaying the colorMap of the model with and without SRGBtoLINEAR() yields inconsistent results between mine and this project:
**This Project**
_Without SRGBtoLINEAR_
 ![SWnoSRGB2Lin](https://github.com/SaschaWillems/Vulkan-glTF-PBR/assets/16941640/36b8974d-2166-4ea3-8707-bc9a64f1a5e4)
_With SRGBtoLINEAR_
![SWwithSRGB2Lin](https://github.com/SaschaWillems/Vulkan-glTF-PBR/assets/16941640/d5e99641-afbc-4298-a719-41ca5c1032d3)

**My Project**
_Without SRGBtoLINEAR_
![YTnoSRGB2Lin](https://github.com/SaschaWillems/Vulkan-glTF-PBR/assets/16941640/925bd1ea-55a2-4ada-bb1f-552502b7a494)
_With SRGBtoLINEAR_
![YTwithSRGB2Lin](https://github.com/SaschaWillems/Vulkan-glTF-PBR/assets/16941640/5274281e-5814-40ae-a42c-d1fad914a8a9)

This project's _With SRGBtoLINEAR_ is similar to my projects _Without SRGBtoLINEAR_.
What could be the reason(s) behind this behaviour?
Again, this is just sampling the colorMap texture and sending it as fragment output.

**Comment by SaschaWillems** [comment]
Hard to judge, but it could either be that you use a different (swapchain) image format or that your image loader already does some kind of conversion.

**Comment by kyamant** [comment]
Thank you for your response.
Unlike your Vulkan repository which prefers B8G8R8A8_UNORM (as does mine), this one prefers B8G8R8A8_SRGB color format during surface initialization. Both use SRGB_Nonlinear_KHR as color space though.
