### ISSUE TITLE
Android tiling lag

### ISSUE THREAD

**Issue by sjfricke** [SaschaWillems/Vulkan-glTF-PBR#7]
First off great demo, works right away on both desktop and android like Vulkan should. The only thing I personally noted with my Galaxy S8 is that if I look around too fast I get some strange artifacts. It looks like the tiling rendering on the mobile device is not all finishing before presenting the next image. I didn't see any mishaps in synchronizations, but wanted to point it out formally.

I ran it through GAPID and when capturing the trace I see it looks normal, so might expect it to be for sure a presentation/swapchain issue as the rendering is shown to be correct on GAPID. I plan to hack at it later after I get another phone with a Mali chip to verify later this week.

![gltf_pbr_binned](https://user-images.githubusercontent.com/9061055/39737564-7320bc14-524b-11e8-8eb0-c25684496dcb.png)

**Comment by SaschaWillems** [comment]
I also do get that on one of the S8s I got here. Works fine on all other Mali based devices including an S7. Haven't had the time to dive deeper into this, but I plan on reporting this to Samsung.

**Comment by SaschaWillems** [comment]
I have forwarded a repo case for this to Samsung. I only get this on Adreno-based S8 devices, Mali-based devices are fine. The synchronization setup is also fairly standard and exactly what was e.g. mentioned in an official Khronos presentation. So I think this could be a driver bug.

**Comment by sjfricke** [comment]
Ok, thanks for verifying it and sending the report!

**Comment by SaschaWillems** [comment]
What Android version is your device running?

**Comment by sjfricke** [comment]
Just rebuilt latest master branch and still confirmed the error is there.

Here are just some general phone settings:

**Model Number:** SM-G950U
**Hardware Version:** REV1.0
**Android Version:** 8.0.0
**Kernel Version:** 4.4.78-13663186
**Build NumbeR:** R16NW.G950USQU4CRE9

**Comment by SaschaWillems** [comment]
I have changed the rendering setup to proper per-frame resources, including uniform buffers, and the tiling lag is no longer present on my Adreno-based S8.

Can you check again?

**Comment by sjfricke** [comment]
Sorry, totally forgot about this, pulled out old device and tried, it works! Thanks for your debugging!
