### ISSUE TITLE
source code formatter(e.g. .clang-format) available?

### ISSUE THREAD

**Issue by syoyo** [SaschaWillems/Vulkan-glTF-PBR#75]
Can we have a source code format settings for Vulkan-glTF-PBR(especially `.clang-format`)

**Comment by SaschaWillems** [comment]
I'm not using any explicit source formatting tool for that project aside from what my IDE (MSVC) does. I also have no plan to add clang-format or something similar.

**Comment by SaschaWillems** [comment]
Sure :)

**Comment by syoyo** [comment]
Thanks!
