### ISSUE TITLE
Not seen the model

### ISSUE THREAD

**Issue by iFreet1** [SaschaWillems/Vulkan-glTF-PBR#8]
The SkyBox is visible, but the model is not visible.

Platform is windows 10, using vulkan sdk version (1.0.68.0) and built with visual studio 2017.
GPU GTX1060.

Any ideas what might be going on?

Thanks!

**Comment by SaschaWillems** [comment]
Can you add some details? What driver version? Do you get any validation messages? Can you try running it through RenderDoc and see if it works there? I have tested on Win10 with an GTX980 and on Linux using an integrated IGP and both worked.

**Comment by iFreet1** [comment]
Version of the driver 398.36 (last). I didn't receive messages about problems of validation. I will try RenderDoc later. 
As a result it:
![no_visible](https://user-images.githubusercontent.com/36539699/41935075-2b867ade-7991-11e8-8b2a-8d793098c895.png)

**Comment by SaschaWillems** [comment]
Just updated to that driver version too and it works fine for me. Maybe the camera is just off? Should be easily visible in RenderDoc.

**Comment by iFreet1** [comment]
In any assembly. I have found one more similar situation, in an example of "skeletalanimation" from "vulkanExamples" occurs too most (a floor is visible, but there is no animated model), at the same time other examples work normally.

**Comment by SaschaWillems** [comment]
Then this may be a driver related problem. The shaders between this and the skeletal animation sample have som similarities.

**Comment by iFreet1** [comment]
Yes, probably the problem was in the line jointMatrix [128]. After correction on 64 as in a shader, the model became visible. I will mean, thanks.

**Comment by SaschaWillems** [comment]
Thanks for letting me know. I checked that in accidentally and only noticed because some models would no longer animated for me.
