### ISSUE TITLE
GUI non-functional on macOS 12.7.4 

### ISSUE THREAD

**Issue by rgosens2** [SaschaWillems/Vulkan-glTF-PBR#81]
Builds but Imgui not working.

**Comment by SaschaWillems** [comment]
I don't own any Apple device and as such can't support them. If this needs fixing, feel free to provide a PR.

**Comment by rgosens2** [comment]
Mouse y coordinate is reversed (moving mouse down moves pointer up). I'll look into it.

**Comment by rgosens2** [comment]
In base/VulkanExampleBase.cpp add:

- (NSPoint)getMouseLocalPoint:(NSEvent*)event
{
	NSPoint location = [event locationInWindow];
	NSPoint point = [self convertPoint:location fromView:nil];
	point.y = self.frame.size.height - point.y;
	return point;
}

And change:

NSPoint point = [self convertPoint:location fromView:nil];
to:
auto point = [self getMouseLocalPoint:event];

**Comment by SaschaWillems** [comment]
#84 has been merge, which I guess should fix this.
