### ISSUE TITLE
Unfreed memory

### ISSUE THREAD

**Issue by rextimmy** [SaschaWillems/Vulkan-glTF-PBR#9]
Hi there sascha,

Just noticed in VulkanglTFModel.hpp there a few vectors that hold pointers and they are not deleted anywhere. https://github.com/SaschaWillems/Vulkan-glTF-PBR/blob/master/base/VulkanglTFModel.hpp#L366 & https://github.com/SaschaWillems/Vulkan-glTF-PBR/blob/master/base/VulkanglTFModel.hpp#L537

**Comment by syoyo** [comment]
I think this issue will be solved once PR https://github.com/SaschaWillems/Vulkan-glTF-PBR/pull/36 has been merged.

**Comment by IAmNotHanni** [comment]
(Can this issue be closed now?)
